[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protocol = { path = "../protocol" }
parking_lot = "0.12.1"
boolinator = "2.4.0"
colour = "0.6.0"
tokio = { version = "1.23.0", features = ["full"] }
async-trait = "0.1.60"
futures = "0.3.25"